name: Lint code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clear npm cache
        run: npm cache clean --force # Add this step

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint
